name: Build and test

on:
  push:
    branches:
    - "master"
    tags: [ "v*" ]
  pull_request:
    branches: [ master ]

env:
  GRADLE_ARGS: "--info --stacktrace"


jobs:
  unit-tests:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11]
    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl
      run: |
        sudo apt-get -y update
        sudo apt-get -y --no-install-recommends install libcurl4 libcurl4-openssl-dev

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Cache Kotlin Native
      uses: actions/cache@v2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-konan

    - name: Run linter
      run: |
        set -eux
        ./gradlew detekt $GRADLE_ARGS

    - name: Run unit tests
      run: |
        set -eux
        ./gradlew allTests -x integ-tests:allTests $GRADLE_ARGS

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  integ-tests:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11]
        es-version: [6.8.18, 7.14.1]
    services:
      elasticsearch:
        image: elasticsearch:${{ matrix.es-version }}
        ports:
        - 9200:9200
        options: >-
          -e="discovery.type=single-node"
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10
    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl
      run: |
        sudo apt-get -y update
        sudo apt-get -y --no-install-recommends install libcurl4 libcurl4-openssl-dev

    - name: Set up Java ${{ matrix.python-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    ### Cache ###
    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Cache Kotlin Native
      uses: actions/cache@v2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-konan
    ### End of Cache ###

    - name: Run integration tests
      run: |
        set -eux
        # JS integration tests are not working at the moment
        ./gradlew :integ-tests:check -x :integ-tests:jsNodeTest $GRADLE_ARGS

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  publish:
    if: |
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: integ-tests
    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl
      run: |
        sudo apt-get -y update
        sudo apt-get -y --no-install-recommends install libcurl4 libcurl4-openssl-dev

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: 11

    ### Cache ###
    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Cache Kotlin Native
      uses: actions/cache@v2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-konan
    ### End of Cache ###

    - name: Prepare publishing
      run: |
        set -eux
        echo '${{ secrets.SIGNING_KEY_CONTENT }}' | base64 -d > signing.gpg

    - name: Publish
      if: |
        github.event_name == 'push' &&
        startsWith(github.ref, 'refs/tags/v')
      run: |
        set -eux
        ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository \
          $GRADLE_ARGS \
          -Psigning.secretKeyRingFile="$PWD/signing.gpg" \
          -Psigning.keyId='${{ secrets.SIGNING_KEY_ID }}' \
          -Psigning.password='${{ secrets.SIGNING_KEY_PASSPHRASE }}' \
          -PsonatypeUser='${{ secrets.SONATYPE_USER }}' \
          -PsonatypePassword='${{ secrets.SONATYPE_PASSWORD }}'
