name: Deploy documentation

on:
  push:
    branches:
    - master
    - docs
    tags:
    - "v*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # We need to fetch last tag for version
        fetch-depth: 0

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    ### Cache ###
    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Cache Kotlin Native
      uses: actions/cache@v2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'buildSrc') }}
        restore-keys: ${{ runner.os }}-konan
    ### End of Cache ###

    - name: Build docs
      run: ./gradlew mkdocsBuild --info

    - name: Build API docs
      run: ./gradlew dokkaHtml --info

    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/mkdocs
        # keep_files: true
        full_commit_message: Publish documentation
